 require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/keywords", type: :request do
  
  # current_user.keywords. As you add validations to Keyword, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    build(:keyword).attributes
  }

  let(:invalid_attributes) {
    build(:keyword, value: '').attributes
  }

  let(:current_user) { create(:user) }

  before :each do
    sign_in current_user
  end

  describe "GET /index" do
    it "renders a successful response" do
      current_user.keywords.create! valid_attributes.merge(value: 'Xmas')
      get keywords_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      keyword = current_user.keywords.create! valid_attributes.merge(value: 'Cricket')
      get keyword_url(keyword)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do      
      get new_keyword_url      
      expect(response).to be_successful
    end
  end

  describe "GET /new_upload" do
    it "renders a successful response" do
      get new_upload_keywords_path
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "render a successful response" do
      keyword = current_user.keywords.create! valid_attributes.merge(value: 'Football')
      get edit_keyword_url(keyword)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      let(:ipad_result) do
        {
          status: true,
          value: 'ipad',
          hits: 1_000_000,
          html: ['<div>Found </div>'],
          links: ["<a href='google.com'>Results</>"],
          search_time: '0.45',
          stats: 'About 1,000,000 results in (0.45 seconds)',
          next_page: [],
          response: {
            next_page: [],
            items: []
          }
        }
      end
      before :each do
        allow(Google::Search).to receive(:new).and_call_original
      end
      it "creates a new Keyword" do
        allow_any_instance_of(Google::Search).to receive(:search).with('ipad').and_return([true, ipad_result])
        expect {
          post keywords_url, params: { keyword: valid_attributes.merge(value: 'ipad') }
        }.to change(Keyword, :count).by(1)
      end
    end

    context "with invalid parameters" do
      it "does not create a new Keyword" do
        expect {
          post keywords_url, params: { keyword: invalid_attributes }
        }.to change(Keyword, :count).by(0)
      end

      it "renders a successful response (i.e. to display the 'new' template)" do
        post keywords_url, params: { keyword: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        valid_attributes.merge(value: 'south india update')
      }

      it "updates the requested keyword" do
        keyword = current_user.keywords.create! valid_attributes.merge(value: 'south india')        
        patch keyword_url(keyword), params: { keyword: new_attributes }
        keyword.reload
        expect(keyword.value).to eq('south india update')
      end

      it "redirects to the keyword" do
        keyword = current_user.keywords.create! valid_attributes.merge(value: 'north india')        
        patch keyword_url(keyword), params: { keyword: new_attributes }
        keyword.reload
        expect(response).to redirect_to(keyword_url(keyword))
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested keyword" do
      keyword = current_user.keywords.create! valid_attributes.merge(value: 'USA')
      expect {
        delete keyword_url(keyword)
      }.to change(Keyword, :count).by(-1)
    end

    it "redirects to the keywords list" do
      keyword = current_user.keywords.create! valid_attributes.merge(value: 'Austria')
      delete keyword_url(keyword)
      expect(response).to redirect_to(keywords_url)
    end
  end

  describe "Bulk Upload /bulk_upload" do
    context "while uploading csv file" do
      before :each do
        @file = fixture_file_upload("#{Rails.root}/public/keyword_1.csv")
      end

      it "should render successful response" do
        post bulk_upload_keywords_path, params: { file: @file }
        expect(response).to be_successful
      end

      it "should parse csv" do
        post bulk_upload_keywords_path, params: { file: @file }
        expect(response.body.to_s).to include('Nas')
      end
    end

    context 'when no file' do
      it "should not create keywords" do
        post bulk_upload_keywords_path, params: { file: nil }
        expect(response.body).to include('created : 0 keyword(s)')
      end
    end
  end
end
